### ISSUE TITLE
Fix 

### ISSUE THREAD

**Issue by daniel-vera-g** [fsiwi-hka/iwi-website#198]

**Comment by daniel-vera-g** [comment]
Related:
```
> iwi-website@0.0.1 dev
> next

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://nextjs.org/docs/messages/react-version
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports.__webpack_modules__.15660.module.exports (/Users/d.veragillard/workspace/fachschaft/iwi-website/node_modules/next/dist/compiled/webpack/bundle4.js:111680:62)
    at NormalModule._initBuildHash (/Users/d.veragillard/workspace/fachschaft/iwi-website/node_modules/next/dist/compiled/webpack/bundle4.js:85092:16)
    at handleParseError (/Users/d.veragillard/workspace/fachschaft/iwi-website/node_modules/next/dist/compiled/webpack/bundle4.js:85146:10)
    at /Users/d.veragillard/workspace/fachschaft/iwi-website/node_modules/next/dist/compiled/webpack/bundle4.js:85178:5
    at /Users/d.veragillard/workspace/fachschaft/iwi-website/node_modules/next/dist/compiled/webpack/bundle4.js:85033:12
    at /Users/d.veragillard/workspace/fachschaft/iwi-website/node_modules/next/dist/compiled/webpack/bundle4.js:51096:3
    at iterateNormalLoaders (/Users/d.veragillard/workspace/fachschaft/iwi-website/node_modules/next/dist/compiled/webpack/bundle4.js:50937:10)
    at Array.<anonymous> (/Users/d.veragillard/workspace/fachschaft/iwi-website/node_modules/next/dist/compiled/webpack/bundle4.js:50928:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.5.0
```

https://stackoverflow.com/a/73027407
