### ISSUE TITLE
Build fails while getting Google Calendar API data

### ISSUE THREAD

**Issue by SimonKienzler** [fsiwi-hka/iwi-website#99]
Both locally and in GitHub Actions, the `npm run build` command fails because the asynchronous call to the Google Calendar API fails. It's not an issue with the service account, we double-checked and replaced the `credentials.json` file.

Surprisingly, this doesn't occur when using `npm run dev`, the calendar data loads just fine in this case.

Needs further investigation. We fixed it temporarily by disabling the calendar integration altogether in #98 - if the issue is fixed, this commit can just be reverted to restore the calendar feature.

Issue Detail:

```
Error: Not Found
    at Gaxios._request (/home/runner/work/iwi-website/iwi-website/node_modules/gaxios/build/src/gaxios.js:127:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Unfortunately, this is not very helpful...

**Comment by SimonKienzler** [comment]
@Blizzardcool would be great if you could try to reproduce this locally and confirm I'm not mistaken here...

**Comment by dustinsommerfeld** [comment]
@mapelpapel Where can i find the `credentials.json` file? Thank you!

**Comment by mapelpapel** [comment]
@dustinsommerfeld sent it to you on Slack
